# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbDBHQCxxRNZZ4cCke5K96QbevDexFmM
"""

import streamlit as st
import joblib
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\\S+", "", text)
    text = re.sub(r"@\\w+", "", text)
    text = re.sub(r"[^a-zA-Z\\s]", "", text)
    text = re.sub(r"\\s+", " ", text).strip()
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words("english"))
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

# واجهة Streamlit
st.set_page_config(page_title="Sentiment Analysis", page_icon="💬")
st.title("🔍 Tweet Sentiment Analyzer")
st.markdown("Write a tweet, and we'll tell you if it's positive or negative!")

user_input = st.text_area("✍️ Type your tweet here:")

if st.button("Analyze Tweet"):
    if user_input.strip() == "":
        st.warning("⚠️ Please enter a tweet.")
    else:
        clean = clean_text(user_input)
        vectorized = vectorizer.transform([clean])
        prediction = model.predict(vectorized)
        if prediction[0] == 1:
            st.success("✅ Positive tweet! 😊")
        else:
            st.error("❌ Negative tweet! 😞")


# حفظ الكود في app.py
with open("app.py", "w") as f:
    f.write(app_code)

!streamlit run app.py &>/content/logs.txt &

# تثبيت pyngrok وتشغيل Streamlit
!pip install pyngrok --quiet

from pyngrok import ngrok

!streamlit run app.py &>/content/logs.txt &

# فتح نفق ngrok على البورت 8501 (ده البورت اللي بيشتغل عليه streamlit)
public_url = ngrok.connect(8501)
print("🔗 Your app is live at:", public_url)

